server:
  port: ${SERVER_PORT:80}

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:student_db}
    username: ${DB_USER:student_db_user}
    password: ${DB_PASS:student_db_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect