server:
  port: ${SERVER_PORT:80}
  address: 0.0.0.0
#  servlet:
#    contextPath: /student

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:172.31.31.56}:${DB_PORT:5432}/${DB_NAME:vehicle_db}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://${DB_HOST:172.31.31.56}:${DB_PORT:5432}/${DB_NAME:vehicle_db}
    user: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASE_LINE:true}
    validate-on-migrate: ${FLYWAY_VALIDATE:true}
    out-of-order: ${FLYWAY_OUT_OF_ORDER:false}
    placeholderReplacement: false
    placeholders:
      application_user: ${DB_USER:postgres}

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

swagger:
  base-url: ${SWAGGER_BASE_URL:http://51.20.192.129:80}


app-config:
  minio:
    url: ${MINIO_URL:https://api.dev.partnerspay.co}
    bucket-name: ${MINIO_BUCKET:pp-data-dev}
    access-key: ${MINIO_ACCESS_KEY:9lYVYDgHnR6SaxRH}
    secret-key: ${MINIO_SECRET_KEY:EwgGePr2J7bvJT8GsodcDlDj6x14Th0P}

microservices:
  doc-generator:
    url: ${DOC_GENERATOR_URL:http://2.76.163.207:80}